# Generated by Django 5.2.2 on 2025-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('age_group', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('sport', models.CharField(blank=True, max_length=15)),
                ('coach', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
