# Generated by Django 5.2.2 on 2025-09-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='gender',
        ),
    ]
